# Generated by Django 6.0.6 on 2026-07-06 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(help_text="ID oficial en la API de CoinGecko (ej: 'bitcoin')", max_length=50, unique=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('condition', models.CharField(choices=[('ABOVE', 'Por encima de'), ('BELOW', 'Por debajo de')], max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la alerta está operativa')),
                ('is_triggered', models.BooleanField(default=False, help_text='Evita que se envíen múltiples mails repetidos si el precio se mantiene')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='finanzas.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
